#!/usr/bin/env python3
"""Own one Obsidian snippet; preserve active theme, fonts, plugins and other CSS.

The fourteen stop weights follow the maintainer's Carbon Cyan / Border palette.
An installed active cc-p00..13 ramp refines those weights before each application.
No note contents are read. Input/output is one JSON document on stdio.
"""
import colorsys,json,os,re,stat,sys,tempfile
from pathlib import Path
SNIPPET='99_Hadalis_Theme'
WEIGHTS=[0,.012,.038,.073,.113,.167,.228,.310,.402,.506,.621,.748,.886,1]
def read_json(path,default=None):
 if not path.exists() and default is not None:return default
 value=json.loads(path.read_text())
 if not isinstance(value,dict):raise ValueError('Configuration must be a JSON object')
 return value

def resolve_paths(payload):
 app_config=Path(os.path.expanduser(str(payload.get('applicationConfigPath') or os.environ.get('XDG_CONFIG_HOME',str(Path.home()/'.config'))+'/obsidian')))
 vault=str(payload.get('vaultPath') or '').strip()
 if not vault:
  state=read_json(app_config/'obsidian.json',{})
  vaults=[v for v in state.get('vaults',{}).values() if isinstance(v,dict) and v.get('path')]
  selected=next((v for v in vaults if v.get('open')),vaults[0] if len(vaults)==1 else None)
  if selected:vault=selected['path']
 if not vault:raise ValueError('Choose an Obsidian vault')
 vault=Path(os.path.expanduser(vault)).resolve()
 if not vault.is_dir():raise ValueError('Vault folder does not exist')
 cfg=Path(os.path.expanduser(str(payload.get('configPath') or '.obsidian')))
 if not cfg.is_absolute():cfg=vault/cfg
 cfg=cfg.resolve()
 if not cfg.is_dir():raise ValueError('Obsidian configuration folder does not exist')
 return vault,cfg

def rgb(value):
 value=str(value)
 if not re.fullmatch(r'#[a-fA-F0-9]{6}',value):raise ValueError('Palette colors must be opaque hexadecimal RGB values')
 return tuple(int(value[i:i+2],16)/255 for i in (1,3,5))
def hex_rgb(value):return '#'+''.join(f'{max(0,min(255,round(channel*255))):02x}' for channel in value)
def mix(a,b,weight):return tuple(x+(y-x)*weight for x,y in zip(a,b))
def weights(cfg,appearance):
 colors={};theme=str(appearance.get('cssTheme') or '')
 # A theme/snippet name is a single filename segment, never an arbitrary path.
 names=[cfg/'themes'/theme/'theme.css'] if theme and theme not in {".",".."} and Path(theme).name==theme else []
 for name in appearance.get('enabledCssSnippets',[]):
  if isinstance(name,str) and name not in {SNIPPET,"",".",".."} and Path(name).name==name:names.append(cfg/'snippets'/(name+'.css'))
 for path in names[:33]:
  if path.is_file() and path.stat().st_size<=1024*1024:
   for index,color in re.findall(r'--cc-p(\d{2})\s*:\s*(#[a-fA-F0-9]{6})\s*;',path.read_text(errors='replace')):colors[int(index)]=rgb(color)
 if all(i in colors for i in range(14)):
  light=[colorsys.rgb_to_hls(*colors[i])[1] for i in range(14)]
  if light[-1]>light[0] and all(a<=b for a,b in zip(light,light[1:])):
   return [(value-light[0])/(light[-1]-light[0]) for value in light],'active Carbon Cyan'
 return WEIGHTS,'Carbon Cyan gradient'

def make_css(palette,stops):
 base,ink,accent=(rgb(palette.get(key,'')) for key in ['background','foreground','accent'])
 # Quiet surfaces follow the existing ramp; a small accent tint keeps layers
 # related to the shell without saturating text or changing luminance order.
 ramp=[hex_rgb(mix(mix(base,ink,t),accent,.055*4*t*(1-t))) for t in stops]
 values={f'cc-p{i:02}':color for i,color in enumerate(ramp)}
 values['cc-accent']=hex_rgb(accent)
 aliases={'border-theme-base':'cc-p00','border-theme-pane':'cc-p01','border-theme-grid':'cc-p03','border-theme-mark':'cc-p04','border-theme-yellow':'cc-p06','border-theme-text':'cc-p10','border-theme-accent':'cc-accent','border-theme-muted':'cc-p11','default-text-color':'cc-p12','highlight':'cc-accent','shadow':'cc-p00','background-primary':'cc-p02','background-primary-alt':'cc-p03','background-secondary':'cc-p01','background-secondary-alt':'cc-p00','background-modifier-border':'cc-p05','background-modifier-border-hover':'cc-p07','background-modifier-form-field':'cc-p03','text-normal':'cc-p12','text-muted':'cc-p10','text-faint':'cc-p08','text-accent':'cc-accent','interactive-accent':'cc-accent','interactive-accent-hover':'cc-p11','color-accent':'cc-accent'}
 lines=['/* Generated by Hadalis. Disable this snippet to restore the active theme. */','body.theme-dark, body.theme-light {']
 lines += [f'  --{key}: {value} !important;' for key,value in values.items()]
 lines += [f'  --{key}: var(--{value}) !important;' for key,value in aliases.items()]
 lines += [f'  --color-accent-rgb: {", ".join(str(round(v*255)) for v in accent)} !important;','}','']
 return '\n'.join(lines)

def atomic_write(path,data):
 if path.exists() and path.read_bytes()==data:return False
 path.parent.mkdir(parents=True,exist_ok=True)
 mode=stat.S_IMODE(path.stat().st_mode) if path.exists() else 0o600
 fd,name=tempfile.mkstemp(prefix='.'+path.name+'.',dir=path.parent)
 try:
  with os.fdopen(fd,'wb') as stream:
   os.fchmod(stream.fileno(),mode);stream.write(data);stream.flush();os.fsync(stream.fileno())
  os.replace(name,path)
 finally:
  if os.path.exists(name):os.unlink(name)
 return True

def update_enabled(path,enabled):
 # Re-read immediately before merging. Retry if Obsidian saves while the
 # candidate is being prepared; never replace its unrelated preferences.
 for attempt in range(3):
  before=path.read_bytes() if path.exists() else b''
  value=json.loads(before or b'{}')
  if not isinstance(value,dict):raise ValueError('Appearance configuration must be a JSON object')
  entries=value.get('enabledCssSnippets',[])
  if not isinstance(entries,list):raise ValueError('CSS snippet selection must be a list')
  selected=[name for name in entries if name!=SNIPPET]
  if enabled:selected.append(SNIPPET)
  if selected==entries:return False
  value['enabledCssSnippets']=selected
  data=(json.dumps(value,ensure_ascii=False,indent=2)+'\n').encode()
  if (path.read_bytes() if path.exists() else b'')!=before:continue
  return atomic_write(path,data)
 raise ValueError('Obsidian is updating its appearance; try again')

def execute(payload):
 vault,cfg=resolve_paths(payload);appearance_file=cfg/'appearance.json';appearance=read_json(appearance_file,{})
 stops,profile=weights(cfg,appearance)
 result={'ok':True,'vaultPath':str(vault),'configPath':str(cfg),'activeTheme':appearance.get('cssTheme') or 'Default','profile':profile,'enabled':SNIPPET in appearance.get('enabledCssSnippets',[]),'changed':False}
 action=payload.get('action','inspect')
 if action=='apply':
  css=make_css(payload.get('palette',{}),stops)
  changed=atomic_write(cfg/'snippets'/(SNIPPET+'.css'),css.encode())
  result.update(changed=update_enabled(appearance_file,True) or changed,enabled=True)
 elif action=='disable':result.update(changed=update_enabled(appearance_file,False),enabled=False)
 elif action!='inspect':raise ValueError('Unsupported theme action')
 return result
if __name__=='__main__':
 try:
  payload=json.loads(sys.stdin.read(32769))
  if not isinstance(payload,dict):raise ValueError('Request must be an object')
  print(json.dumps(execute(payload),ensure_ascii=False))
 except (OSError,ValueError,TypeError,KeyError) as error:
  print(json.dumps({'ok':False,'error':str(error)}));sys.exit(1)
