[workspace]
resolver = "2"
members = [
    "crates/inir-protocol",
    "inir-inputd",
    "inir-mpdd",
    "inir-native",
    "inir-theme",
]

[workspace.package]
edition = "2024"
license = "GPL-3.0-or-later"
rust-version = "1.95"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
evdev = { version = "0.13.2", features = ["serde"] }
html-escape = "0.2"
kdl = { version = "6.7.1", features = ["v1-fallback"] }
libc = "0.2"
regex = "1.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
sha2 = "0.10"
