[package]
name = "inir-theme"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
image = { version = "0.25.9", default-features = true }
material-color-utils = { version = "0.1.3", default-features = false, features = ["image"] }
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
toml = "0.9"
