#!/usr/bin/env python3
"""Explicit Arch-only Hadalis system gateway package bootstrap.

Used by a user click in Hadalis Settings on repo-copy installs. Build *without*
root, using two fixed-digest Hadalis files and an in-memory PKGBUILD. Only
pkexec pacman -U performs the privileged installation. No remote payload,
downloaded script, shell, or arbitrary user path executes as root.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = "inir-hadalird-gateway"
FILES = {
    "assets/helpers/inir-hadalird-system-provision": (
        "usr/libexec/inir-hadalird-system-provision",
        "8bb000cad718cec4130ead90971dfd66f3718f9a5065d31d9671acb9d4a2c0c6", 0o755),
    "assets/polkit/org.inir.hadalird-system-provision.policy": (
        "usr/share/polkit-1/actions/org.inir.hadalird-system-provision.policy",
        "a979291e099e1fa0f2310b616451da86f0aa9ab898ed875b0b6b601b282a56c9", 0o644),
}
PKGBUILD = """# Generated by the audited Hadalis gateway bootstrap. No install script.
pkgname=inir-hadalird-gateway
pkgver=0.1.0
pkgrel=1
pkgdesc='Optional trusted Hadalird Polkit gateway for source-installed Hadalis'
arch=('any')
url='https://github.com/llocphann/Hadalis'
license=('GPL-3.0-only')
depends=('python' 'polkit')
source=()
sha256sums=()
package() {
  install -Dm755 "$startdir/payload/inir-hadalird-system-provision" "$pkgdir/usr/libexec/inir-hadalird-system-provision"
  install -Dm644 "$startdir/payload/org.inir.hadalird-system-provision.policy" "$pkgdir/usr/share/polkit-1/actions/org.inir.hadalird-system-provision.policy"
}
"""
METADATA = {".PKGINFO", ".BUILDINFO", ".MTREE"}
MAX_RESULT = 4096


def digest(data):
    return hashlib.sha256(data).hexdigest()


def run(command, *, cwd=None, timeout=15):
    try:
        return subprocess.run(command, cwd=cwd, capture_output=True, text=True,
                              timeout=timeout, check=False)
    except (FileNotFoundError, subprocess.TimeoutExpired) as error:
        raise ValueError("Gateway package tool unavailable or timed out: " + command[0]) from error


def installed(name):
    return run(["/usr/bin/pacman", "-Qq", name]).returncode == 0


def expected_files(root):
    out = {}
    for name, (dest, sha, mode) in FILES.items():
        path = root / name
        if path.is_symlink() or not path.is_file():
            raise ValueError("Missing or linked trusted Hadalis source: " + name)
        content = path.read_bytes()
        if digest(content) != sha:
            raise ValueError("Hadalis system gateway source hash mismatch: " + name)
        out[dest] = (content, mode, sha)
    return out


def system_state():
    exists = {p: Path("/" + d).is_file() for d, _, _ in FILES.values()}
    hashes = all(exists[d] and digest(Path("/" + d).read_bytes()) == sha
                 for d, sha, _ in FILES.values())
    owned = installed(PACKAGE)
    return {"packageInstalled": owned, "sourcePackageAvailable": True,
            "installed": owned and hashes,
            "diagnostic": "ready" if owned and hashes else
                "modified" if owned else "not-installed"}


def build_package(root, directory, command=run, extract=None):
    payload = expected_files(root)
    path = Path(directory)
    stage = path / "payload"
    stage.mkdir()
    for dest, (content, mode, _) in payload.items():
        target = stage / Path(dest).name
        target.write_bytes(content)
        target.chmod(mode)
    (path / "PKGBUILD").write_text(PKGBUILD, encoding="utf-8")
    result = command(["/usr/bin/makepkg", "--force", "--noconfirm"], cwd=path, timeout=180)
    if result.returncode != 0:
        raise ValueError("makepkg could not build the trusted gateway: " + result.stderr[-MAX_RESULT:])
    packages = list(path.glob(PACKAGE + "-*.pkg.tar.*"))
    if len(packages) != 1:
        raise ValueError("Gateway build produced an unexpected package count")
    pkg = packages[0]
    names = command(["/usr/bin/bsdtar", "-tf", str(pkg)], timeout=30)
    if names.returncode != 0:
        raise ValueError("Cannot inspect the newly built gateway package")
    allowed = set(METADATA) | set(payload)
    for name in names.stdout.splitlines():
        normalized = name.removeprefix("./").rstrip("/")
        if not normalized:
            continue
        if normalized not in allowed and not any(
                x.startswith(normalized + "/") for x in payload):
            raise ValueError("Unexpected file in system gateway package: " + normalized)
    for dest, (_, _, sha) in payload.items():
        if extract is None:
            content = subprocess.run(["/usr/bin/bsdtar", "-xOf", str(pkg), dest],
                                     capture_output=True, timeout=30, check=False)
        else:
            content = extract(pkg, dest)
        if content.returncode != 0 or digest(content.stdout) != sha:
            raise ValueError("Built system package does not match trusted gateway bytes: " + dest)
    return pkg


def install(root=ROOT, command=run):
    if os.geteuid() == 0:
        raise ValueError("Gateway package builds must run as an unprivileged user")
    for tool in ("/usr/bin/pacman", "/usr/bin/makepkg", "/usr/bin/bsdtar", "/usr/bin/pkexec"):
        if not os.path.isfile(tool) or not os.access(tool, os.X_OK):
            raise ValueError("Required Arch system-package tool missing: " + tool)
    if installed("inir-shell") or installed("inir-shell-git"):
        raise ValueError("Arch shell package already owns this gateway; upgrade the shell package instead")
    if installed(PACKAGE) and system_state()["installed"]:
        return {"ok": True, **system_state(), "message": "System gateway package is already installed"}
    if installed(PACKAGE) and not system_state()["installed"]:
        raise ValueError("Existing managed system gateway is modified; refusing overwrite")
    for dest, _, _ in FILES.values():
        target = Path("/" + dest)
        if target.exists() or target.is_symlink():
            raise ValueError("A different installation already owns: " + str(target))
    with tempfile.TemporaryDirectory(prefix="hadalis-gateway-") as folder:
        package = build_package(root, folder, command=command)
        # This is the ONLY privileged action. Package contains no .INSTALL,
        # no arbitrary files and has been checked against two SHA-256 pins.
        result = command(["/usr/bin/pkexec", "/usr/bin/pacman",
                          "-U", "--noconfirm", "--", str(package)], timeout=120)
        if result.returncode != 0:
            raise ValueError("Gateway installation cancelled or failed: " + result.stderr[-MAX_RESULT:])
    state = system_state()
    if not state["installed"]:
        raise ValueError("System package operation returned without a verified installed gateway")
    return {"ok": True, **state, "message": "Trusted system gateway installed; hardware helpers remain opt-in"}


def remove(command=run):
    if not installed(PACKAGE):
        return {"ok": True, **system_state(), "message": "Standalone gateway package was not installed"}
    # Never remove the gateway while its owned helper files might still be in use.
    provisioner = Path("/usr/libexec/inir-hadalird-system-provision")
    status = command([str(provisioner), "status"], timeout=12)
    try:
        current = json.loads(status.stdout.strip())
    except ValueError:
        raise ValueError("Cannot inspect system helper state; preserving gateway package")
    if status.returncode != 0 or current.get("installed") or current.get("managed"):
        raise ValueError("Remove managed TLP/Thinkfan helpers first; preserving gateway package")
    response = command(["/usr/bin/pkexec", "/usr/bin/pacman", "-R",
                        "--noconfirm", PACKAGE], timeout=120)
    if response.returncode != 0:
        raise ValueError("Gateway removal cancelled or failed: " + response.stderr[-MAX_RESULT:])
    return {"ok": True, **system_state(), "message": "Standalone system gateway package removed"}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("action", choices=("status", "install", "remove"))
    args = parser.parse_args()
    try:
        if args.action == "status":
            result = {"ok": True, **system_state()}
        elif args.action == "install":
            result = install()
        else:
            result = remove()
        print(json.dumps(result))
    except (OSError, ValueError, TypeError, subprocess.SubprocessError) as error:
        print(json.dumps({"ok": False, "error": str(error)}))
        raise SystemExit(1)


if __name__ == "__main__":
    main()
