[package]
name = "inir-native"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
html-escape.workspace = true
regex.workspace = true
kdl.workspace = true\nserde.workspace = true\nserde_json.workspace = true\n